### ISSUE TITLE
upstream issue for cryptopp pin?

### ISSUE THREAD

**Issue by edrex** [mirrexagon/espressobin-nix#3]
Hi, just got an espressobinv5 and using your repo to build uboot.

Is there a thread somewhere about why cryptopp is broken?

**Comment by edrex** [comment]
guessing the issue you were working about is fixed in https://github.com/NixOS/nixpkgs/pull/114707, so I may try to unpin tomorrow.

**Comment by mirrexagon** [comment]
There isn't, the pin was a hack to get things working again, which I forgot to revisit later. I don't remember exactly what was broken now, but something in A3700 utils [1] wouldn't build against newer cryptopp - maybe the interface changed. It's possible that A3700 utils has been updated since to fix this.

[1] [githubMarvellEmbeddedProcessors/A3700-utils-marvell](https://github.com/MarvellEmbeddedProcessors/A3700-utils-marvell)

If I get a chance I will have a look at this as well as updating the versions of U-Boot and the other dependencies.

**Comment by edrex** [comment]
IIRC correctly I tried unpinning and saw the build failure. Leave this open to investigate?

**Comment by mirrexagon** [comment]
#7 updates everything so that the current version of cryptopp in nixpkgs works.
