### ISSUE TITLE
bootloader build failure 

### ISSUE THREAD

**Issue by edrex** [mirrexagon/espressobin-nix#5]
hi, I'm having a build failure: https://clbin.com/MAc5p

Nix on Arch amd64 (i don't currently have an amd64 nixos box).

It looks like some /bin/sh lines aren't getting patched somewhere in the arm-trusted-firmware build. Maybe it's running a binary from the repo?

I'm working on factoring out the build deps into their own derivations to make it easier to debug.

**Comment by edrex** [comment]
I ended up using the openwrt firmware build for now (https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa53/)

**Comment by mirrexagon** [comment]
>hi, I'm having a build failure: https://clbin.com/MAc5p

Sorry for taking ages to respond to this. In the meantime, [clbin.com](https://clbin.com) doesn't seem to be up anymore.

>Nix on Arch amd64 (i don't currently have an amd64 nixos box).

Do you mean you didn't have an AArch64 NixOS box? I'm not sure that this actually builds on native AArch64, I have vague memories of there being some x86_64/amd64 binaries that were run, or some similar reason why it wouldn't work. I didn';t really end up looking into it because I haven't needed to build it on AArch64 yet.

The build works fine for me on x86_64:
- This repo commit [48bc807](https://github.com/mirrexagon/espressobin-nix/commit/48bc807c9f992451cdb9148407c1ce89f54e14bd)
- Nixpkgs commit [e10da1c](https://github.com/nixos/nixpkgs/commit/e10da1c)

>I ended up using the openwrt firmware build for now [...]

I based this project to a large extent on what OpenWRT did actually, so fair enough!

**Comment by edrex** [comment]
> [clbin.com](https://clbin.com/) doesn't seem to be up anymore.
maybe intermittent, i can view the log RN.

> Do you mean you didn't have an AArch64 NixOS box or you didn't have an AMD64 one?

Oops, I meant I didn't have an aarch64 NixOS box.

I still have the board but it suffers from the random reboots so many of these had, so it's in a drawer (https://forum.openwrt.org/t/espressobin-mvebu-cpufreq-still-unstable/112338, but also crashes with workaround). I may take it out for another go this year.

**Comment by edrex** [comment]
I'll close for now since it #worksforyou and I'm not going to try to repro soon. Thanks.
